- name: Install prerequisites for Nagios
  dnf:
    name:
      - httpd
      - php
      - gcc
      - glibc
      - glibc-common
      - gd
      - gd-devel
      - make
      - net-snmp
      - unzip
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install Nagios Plugins on CentOS
  dnf:
    name: nagios-plugins
    state: present
  when: ansible_distribution == 'CentOS'
