- name: Update repository cache
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install prerequisites for Nagios
  apt:
    name:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php7.4
      - libgd-dev
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Install Nagios Plugins on Ubuntu
  apt:
    name: nagios-plugins
    state: present
  when: ansible_distribution == 'Ubuntu'
