- name: Install Nagios on Ubuntu and CentOS
  hosts: all
  become: yes
  roles:
    - role: ubuntu_server
      when: ansible_distribution == 'Ubuntu'

    - role: centos_server
      when: ansible_distribution == 'CentOS'
